# Numpy

#### 1.Создать вектор (одномерный массив) размера 100, заполненный нулями

In [1]:
import numpy as np

In [6]:
np.linspace(0, 0, 100)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 2.Создать вектор размера 100, заполненный единицами

In [10]:
np.linspace(1, 1, 100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### 3.Создать вектор размера 100, заполненный числом 3

In [11]:
np.linspace(3, 3, 100)

array([3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.])

#### 4. Как получить документацию о функции numpy.add из командной строки?

In [ ]:
np.add# + "shift + tab" in jupyter

#### 5. Поменять 2 строки в матрице

In [29]:
b = np.array([[1,3,4,5],[6,7,8,9]])
print(b)
tmp = np.copy(b[0])
 
b[0],b[1] = b[1],b[0]

b[1] = tmp

[[1 3 4 5]
 [6 7 8 9]]


In [30]:
b

array([[6, 7, 8, 9],
       [1, 3, 4, 5]])

#### 6. Создать вектор со значениями от 10 до 100

In [31]:
np.arange(10,100)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

#### 7. Развернуть вектор (первый становится последним)

In [50]:
a = np.arange(1,100)
print(a)
a = a[::-1]
a

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]


array([99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83,
       82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66,
       65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49,
       48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

#### 8. Создать матрицу (двумерный массив) 4x4 со значениями от 0 до 16

In [54]:
a = np.arange(0,16)
a.resize(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

#### 9.  Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [9]:
a = np.array([1,2,3,4,5])
nz = 3
b = np.zeros(17)
b[::4] = a
b

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])

#### 10. Создать 3x3 единичную матрицу

In [10]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 11. Создать массив 3x3x3 со случайными значениями

In [15]:
a = np.random.rand(27)
a = a.reshape(3,3,3)
a

array([[[0.07271644, 0.73817498, 0.16465723],
        [0.79098339, 0.33592892, 0.65203143],
        [0.75602363, 0.2556486 , 0.49063218]],

       [[0.46683881, 0.09665195, 0.28986123],
        [0.17211292, 0.30924515, 0.58254141],
        [0.42524852, 0.56945509, 0.33986   ]],

       [[0.74127867, 0.328595  , 0.42681082],
        [0.56854197, 0.02319295, 0.9643027 ],
        [0.28219173, 0.01412034, 0.0231241 ]]])

#### 12. Создать массив 10x10 со случайными значениями, найти минимум и максимум

In [27]:
a = np.random.rand(100)
a = a.reshape(10,10)
b = np.amin(a)
b
print(np.amax(a))
print(b)

0.9897334933655401
0.002347470188637124


#### 13. Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [28]:
a = np.random.rand(30)
np.mean(a)

0.4494903950965169

#### 14. Создать матрицу с 0 внутри, и 1 на границах

In [35]:
a = np.ones((5,5))
a[1:-1, 1:-1] = 0
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 15. Удивите меня в этом задании, покажите какое нибудь класное преобразование в numpy (не идет в зачет)

#### 16. Создать 5x5 матрицу с 1,2,2,4 под диагональю


In [54]:
a = np.arange(1, 5)
c = np.diag(a,k=-1)
c

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 17. Создать 8x8 матрицу и заполнить её в шахматном порядке

In [67]:
a = np.zeros((8,8))
 
a[::2,::2] = 1
a[1::2,1::2] = 1
a

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

#### 18. Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?

In [77]:
print(np.unravel_index(100, (6, 7,8)))

(1, 5, 4)


#### 19. Создать 8x8 матрицу и заполнить её в шахматном порядке, используя функцию tile

In [75]:
b = np.array([[0,1],[1,0],[0,1],[1,0],[0,1],[1,0],[0,1],[1,0]])
c = np.tile(b,4)
print(c)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Перемножить матрицы 5x3 и 3x2

In [87]:
a = np.arange(15)
a.resize(5,3)
b = np.arange(6)
b.resize(3,2)

a@b

array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

#### 21. Дан массив, поменять знак у элементов, значения которых между 3 и 8

In [3]:
a = np.arange(10)

a[[(a>3)] and [(a<8)]] = -1*a[[(a>3)] and [(a<8)]]
a

/home/pavel/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  This is separate from the ipykernel package so we can avoid doing imports until


array([ 0, -1, -2, -3, -4, -5, -6, -7,  8,  9])

#### 23. Создать 5x5 матрицу со значениями в строках от 0 до 4

In [17]:
a = np.zeros((5,5))
a += np.arange(5)
a

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 24. Есть генератор, сделать с его помощью массив

#### 25. Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [19]:
np.linspace(0.1,0.9,10)

array([0.1       , 0.18888889, 0.27777778, 0.36666667, 0.45555556,
       0.54444444, 0.63333333, 0.72222222, 0.81111111, 0.9       ])

#### 26. Отсортировать вектор

In [21]:
np.sort(np.random.rand(10))

array([0.02276147, 0.11437361, 0.20403472, 0.20621431, 0.32496816,
       0.33880865, 0.51664383, 0.58055222, 0.6057488 , 0.67707356])

#### 27. Проверить, одинаковы ли 2 numpy массива

In [23]:
a = np.arange(5)
b = np.arange(5)
a == b

array([ True,  True,  True,  True,  True])

#### 28. Сделать массив неизменяемым

In [24]:
a = np.arange(10)
a.flags.writeable = False
a[0] = 2

ValueError: assignment destination is read-only

#### 29. Найти n наибольших значений в массиве

In [29]:
a = np.arange(10)
np.sort(a)
a[:n]

array([0, 1, 2, 3])

#### 30. Заменить максимальный элемент на ноль

In [31]:
a = np.random.rand(10)
b = np.amax(a)
a[a==b] = 0
a

array([0.43611925, 0.67669328, 0.39637077, 0.17090931, 0.        ,
       0.58389457, 0.58292752, 0.38475708, 0.18840521, 0.71042095])

#### 31. Создать структурированный массив с координатами x, y на сетке в квадрате [0,1]x[0,1]

#### 32. Из двух массивов сделать матрицу Коши C (Cij = 1/(xi - yj))

In [57]:
a = np.arange(5)

b = a + 2
c = 1.0 / np.subtract.outer(X, Y)
c

array([[-2.        , -0.66666667, -0.4       , -0.28571429, -0.22222222,
        -0.18181818, -0.15384615, -0.13333333],
       [ 2.        , -2.        , -0.66666667, -0.4       , -0.28571429,
        -0.22222222, -0.18181818, -0.15384615],
       [ 0.66666667,  2.        , -2.        , -0.66666667, -0.4       ,
        -0.28571429, -0.22222222, -0.18181818],
       [ 0.4       ,  0.66666667,  2.        , -2.        , -0.66666667,
        -0.4       , -0.28571429, -0.22222222],
       [ 0.28571429,  0.4       ,  0.66666667,  2.        , -2.        ,
        -0.66666667, -0.4       , -0.28571429],
       [ 0.22222222,  0.28571429,  0.4       ,  0.66666667,  2.        ,
        -2.        , -0.66666667, -0.4       ],
       [ 0.18181818,  0.22222222,  0.28571429,  0.4       ,  0.66666667,
         2.        , -2.        , -0.66666667],
       [ 0.15384615,  0.18181818,  0.22222222,  0.28571429,  0.4       ,
         0.66666667,  2.        , -2.        ]])

#### 33. Найти минимальное и максимальное значение, принимаемое каждым числовым типом numpy

In [54]:
 for dtype in [np.int8, np.int32, np.int64]:  
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
-1.7976931348623157e+308
1.7976931348623157e+308


#### 34. Напечатать все значения в массиве

In [34]:
a = np.arange(10)
for i in a:
    print(i)

0
1
2
3
4
5
6
7
8
9


#### 35. Найти ближайшее к заданному значению число в заданном массиве

In [62]:
a = np.arange(10)
idx = (np.abs(a - 1.5)).argmin()
a[idx]

1

#### 36. Преобразовать массив из float в int

In [39]:
a = np.array([1.2, 2.1, 3.25, 11])
a = a.astype(int)
a

array([ 1,  2,  3, 11])

#### 37. Каков эквивалент функции enumerate для numpy массивов?

In [45]:
Z = np.arange(9)
for index, value in np.ndenumerate(Z):
    print(index, value)

(0,) 0
(1,) 1
(2,) 2
(3,) 3
(4,) 4
(5,) 5
(6,) 6
(7,) 7
(8,) 8


#### 38. Случайно расположить p элементов в 2D массив

In [49]:
a = np.ones(10).reshape(2,5)
a
for i in range(p):
    a[np.random]

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

#### 39. Отнять среднее из каждой строки в матрице

In [44]:
a = np.random.rand(1,10)
print(a)
b = a - a.mean(axis=1, keepdims=True)
b

[[0.93148459 0.90902904 0.92114736 0.2490331  0.80143335 0.84212007
  0.33420575 0.37661434 0.75999745 0.24663384]]


array([[ 0.2943147 ,  0.27185915,  0.28397747, -0.38813679,  0.16426347,
         0.20495019, -0.30296414, -0.26055555,  0.12282756, -0.39053605]])

#### 40. Отсортировать матрицу по n-ому столбцу

In [ ]:
np.sort(arr,axis=n)

#### 41. Определить, есть ли в 2D массиве нулевые столбцы

In [65]:
a = np.arange(10).reshape(5,2)
a
print(a.any(axis= 0))

[ True  True]


#### 42. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве (осторожно с повторами)

In [8]:
a = np.zeros(10)

b =  np.random.randint(0,len(a),20)
print(a)
print(b)
a = a + np.bincount(b, minlength = len(a))
a

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[3 8 6 9 5 5 7 7 7 4 2 4 8 5 7 5 6 2 0 6]


array([1., 0., 2., 1., 2., 4., 3., 4., 2., 1.])

#### 43. Дан массив (w,h,3) (картинка) dtype=ubyte, посчитать количество различных цветов

#### 44. Дан четырехмерный массив, посчитать сумму по последним двум осям

#### Доп задания с лекции

In [11]:
# 0. Создать нулевой вектор с 5 значений на 5 позиции 5?


In [20]:
# 1. Создать матрицу 3*3 со значениями от 0 до 8
a = np.arange(0,9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [23]:
# 2. Найти индексы не нулевых элементов в массиве [1,2,0,0,4,0]
a = np.array([1,2,0,0,4,0])
idx = np.where(a == 0)
a[idx]

array([0, 0, 0])

In [34]:
# 3. Матрица 3*3*3 с рандомными значениями
a =  np.random.randint(0,100,27).reshape(3,3,3)
a

array([[[49, 28, 99],
        [27, 11, 50],
        [23, 98, 14]],

       [[94, 66, 52],
        [38, 40, 93],
        [20, 73, 24]],

       [[ 4, 61, 42],
        [59, 78, 20],
        [ 2, 76, 59]]])

In [38]:
# 4. Матриа 10 на 10, найти минимумы и максимумы
a =  np.random.randint(0,100,100).reshape(10,10)
print(a)
_max = np.amax(a)
_min = np.amin(a)
print(_max)
_min

[[18 52 48 37 70  4 98 76 82  5]
 [45 98 40  2 78  4 14 27  8  2]
 [75 27 52 90 89 93 80  3 22 86]
 [75 40 71 24 90 46  2 67 78 90]
 [57 15 64 47 54 86 52 18 18 50]
 [ 8 27  7 43 18 83 95 38 38 37]
 [ 3 88 20 18 65 47 30 83 94 92]
 [51  7 77 29 38 72 22  6 71 24]
 [92 61 69 72 96 50 99 44 22 81]
 [34 46 62 91 60 15 31 52 21 16]]
99


2